[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200
  force = true

[[redirects]]
  from = "/api/weather-latest"
  to = "/.netlify/functions/weather-latest"
  status = 200
  force = true
